// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brisctuamdsbuyognkto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyaXNjdHVhbWRzYnV5b2dua3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTM5OTksImV4cCI6MjA2MDMyOTk5OX0.MqlISY1NhrOUNVYvVK3hrYqUcyjxmulPuVONyNxkskc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);